# prod setting
spring:
  profiles:
    activate:
      on-profile: prod
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://maria-test:3306/myapp
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: create


logging:
  level:
    org:
      springframework:
        jdbc: DEBUG
        security: DEBUG
